### ISSUE TITLE
Starting image format?

### ISSUE THREAD

**Issue by danielfarrell** [ChienliMa/Blends#1]
Just wanted to see what the starting image format needs to be.  Code says the following:

```
3 dimension numpy.ndarray with 3 channels are [ width, height, channel ]
```

I am starting with an RGBA image in Pillow and didn't know if there was a known conversion to get those usable in this.  Thanks.

**Comment by ChienliMa** [comment]
I think the input images have only 3 channels -- RGB. 
And I separate the alpha channel as another input parameters. 
Please have a look a the [blend()](https://github.com/ChienliMa/Blends/blob/master/blends.py#L51) function and its docs.

BTW, this is a program written in my undergraduate study and there may be some mistakes.
And, by replacing lambda with numpy.where(), this code can be faster.

**Comment by danielfarrell** [comment]
Thanks!
